### ISSUE TITLE
Add Error Handler for "x is out of range"  

### ISSUE THREAD

**Issue by millzpaugh** [mapbox/mapbox-tile-copy#112]
`[error] required parameter x is out of range of possible values based on z value` has recently surfaced while looking through upload errors. It's very similar to `required parameter y is out of range`, which is currently handled here https://github.com/mapbox/mapbox-tile-copy/blob/master/lib/tilelivecopy.js#L29

Let's add the `x is out of range` error to this conditional so both `x & y out of range` are handled in the same conditional statement on L29. 

cc @mapsam

**Comment by springmeyer** [comment]
This looks like it landed in https://github.com/mapbox/mapbox-tile-copy/commit/706c7a43cc5310e3efe4bb0d30b601068b475fce
