### ISSUE TITLE
Add tracker for invalid/valid vector tiles

### ISSUE THREAD

**Issue by millzpaugh** [mapbox/mapbox-tile-copy#113]
Add tracker to log the number of invalid/valid vector tiles 
- [ ] Declare env variable
- [ ] Write to system with stats object

Ref https://github.com/mapbox/mapbox-tile-copy/pull/114

**Comment by springmeyer** [comment]
added in https://github.com/mapbox/mapbox-tile-copy/commit/706c7a43cc5310e3efe4bb0d30b601068b475fce
