### ISSUE TITLE
npm install can't get precompiled binaries

### ISSUE THREAD

**Issue by Synesso** [mapbox/mapbox-tile-copy#115]
Similar to #47 

```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.6.2/node-v47-darwin-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.6.2 and node@5.10.1 (node-v47 ABI) (falling back to source compile with node-gyp)
```

But in this case, I am running a supported node version. v5.10.1.

Is there a release tarball at that URL? Should I be authorised to fetch it?

**Comment by Synesso** [comment]
Using this dockerfile I get a different failure, but a failure nontheless.

`FROM ubuntu:artful

USER root

RUN apt update -y
RUN apt install -y \
  curl \
  git

ENV NVM_DIR /root/.nvm

WORKDIR /tmp
RUN git clone https://github.com/mapbox/mapbox-tile-copy.git && \
   cd mapbox-tile-copy && \
   git checkout v6.6.0 && \
   curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash && \
   . $NVM_DIR/nvm.sh && \
   nvm install 5.10.1 && \
   nvm use 5.10.1 && \
   npm install -g @mapbox/mapbox-tile-copy
`

`
npm WARN deprecated tile-stat-stream@1.1.0: Package abandoned, contact support@npmjs.com for more info.
npm WARN deprecated queue-async@1.0.7: renamed to d3-queue
npm WARN deprecated protozero@1.5.1: protozero should no longer be used via npm, install instead via https://github.com/mapbox/mason
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated tiletype@0.2.1: This module is now under the @mapbox namespace: install @mapbox/tiletype instead
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
/root/.nvm/versions/node/v5.10.1/bin/mapbox-tile-copy -> /root/.nvm/versions/node/v5.10.1/lib/node_modules/@mapbox/mapbox-tile-copy/bin/mapbox-tile-copy.js

> gdal@0.9.6 install /root/.nvm/versions/node/v5.10.1/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/gdal
> node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: Permission denied
/root/.nvm/versions/node/v5.10.1/lib
 -- (empty)
`

**Comment by Synesso** [comment]
It's the global install that fails. Local install (like .travis.yml) works.

**Comment by Synesso** [comment]
... but when I attempt to use it:

```
module.js:471
    throw err;
    ^

Error: Cannot find module '@mapbox/mapbox-file-sniff'
    at Function.Module._resolveFilename (module.js:469:15)
```

**Comment by Synesso** [comment]
This config fixed the issue in the docker image
```
npm config set user 0
npm config set unsafe-perm true
```

In full:
```
FROM ubuntu:artful

USER root

RUN apt update -y
RUN apt install -y \
  curl \
  git

ENV NVM_DIR /root/.nvm

WORKDIR /tmp
RUN git clone https://github.com/mapbox/mapbox-tile-copy.git && \
   cd mapbox-tile-copy && \
   curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash && \
   . $NVM_DIR/nvm.sh && \
   nvm install 6

 RUN . $NVM_DIR/nvm.sh && \
   nvm use 6 && \
   npm config set user 0 && \
   npm config set unsafe-perm true && \
   npm install -g @mapbox/mapbox-tile-copy
```

**Comment by springmeyer** [comment]
`npm config set unsafe-perm true` is a 👍 workaround. Or, not running as root (which is an npm issue). Closing this is issue has nothing specific to do with mapbox-tile-copy and rather will present itself with any npm install of a module that has dependencies with need to call out to a program to install themselves, like C++ addons using `node-pre-gyp`.
