### ISSUE TITLE
Update mapnik dependency

### ISSUE THREAD

**Issue by citizenfish** [mapbox/mapbox-tile-copy#144]
At present mapbox-tile-copy requires mapnik 3.7.2 

This is causing a lot of installation issues. We have tried on Windows/Linux/OSX with no success as there are many issues with this earlier version of mapnik.

Mapnik 4.0 installs fine. Could this repo be updated to use the later version?

**Comment by rowanwins** [comment]
Hi @citizenfish ,

you might want to check out [mbtiles-extractor](https://github.com/rowanwins/mbtiles-extractor) which does alot of the same stuff but has simpler dependencies, hope it helps :)

**Comment by mapsam** [comment]
@citizenfish the mapnik version was updated in https://github.com/mapbox/mapbox-tile-copy/pull/143. This will allow you to install either 3.x or 4.x of node-mapnik!
