### ISSUE TITLE
Expand to other copy destinations

### ISSUE THREAD

**Issue by rclark** [mapbox/mapbox-tile-copy#3]
Let's try to consider expanding mapbox-tile-copy into a command that can copy to/from a set of curated tilelive sources. It could basically become `tilelive-copy` without the tilelive.auto-style icky detection of protocols and modules. 

It would be less flexible for new/arbitrary tile sources, but would also have a clearly defined dependency set.

cc @GretaCB @yhahn

**Comment by rclark** [comment]
cc @willwhite

I think to start it would be interesting to pursue pushing to an mbtiles file. A folders-on-the-file-system destination might be another nice touch.

**Comment by willwhite** [comment]
Awesome. mbtiles would be a clear win with potential Atlas customers.

**Comment by yhahn** [comment]
:+1:

**Comment by yhahn** [comment]
Picking this up to help users go from <file> => offline mbtiles source.

**Comment by mtirwin** [comment]
I see @yhahn beat me here. Connecting a separate sales thread that @sgillies had graciously picked up:

mapbox/sales/issues/1324#issuecomment-98805215

Not sure whether @rclark @sgillies or others are best positioned to run with this, but ping me if helpful to discuss some of the use cases and potential customers this feature would support.

**Comment by musicformellons** [comment]
How is this doing? As I understand things this would make converting geojson (local disk) to mbtiles (local disk) possible? Or is that already possible using current version?

**Comment by musicformellons** [comment]
Ah I got:
You must provide a valid S3 url

So current version does not support local conversion...

**Comment by mapsam** [comment]
Looks like things haven't moved on this in a while @musicformellons. For the time being, I recommend checking out [tippecanoe](https://github.com/mapbox/tippecanoe), a command line utility that converts geojson to mbtiles locally and gives you much more precision in terms of simplification and zoom.

**Comment by musicformellons** [comment]
@mapsam Thanks, that is where I ended up!

**Comment by springmeyer** [comment]
👍 to using https://github.com/mapbox/tippecanoe for source -> local mbtiles. Per https://github.com/mapbox/mapbox-tile-copy/pull/99 we may add support for more sinks for testing reasons but not for general use.
