### ISSUE TITLE
Add node version to README

### ISSUE THREAD

**Issue by aboutaaron** [mapbox/mapbox-tile-copy#30]
I was able to get mapbox-tile-copy to install on Node 0.10 but but not 0.12 or io.js 1.2+. It'd be nice if the node version was in the README to make it easier for folks installing.

**Comment by tmcw** [comment]
After https://github.com/mapbox/tilelive-s3/pull/44 is merged, we should have compatibility with node v0.12 and io

**Comment by mapsam** [comment]
Just added the node versions we are testing with to the README: https://github.com/mapbox/mapbox-tile-copy/commit/bd32115e31519a0f47b7d1c36b83d0ffefb97b82
