### ISSUE TITLE
Alternative output formats

### ISSUE THREAD

**Issue by gmaclennan** [mapbox/mapbox-tile-copy#46]
Currently for rasters this creates tiles in `webp` format. This seems to be a current [limitation of tilelive-omnivore](https://github.com/mapbox/tilelive-omnivore/issues/1).

How could I create `jpeg` tiles from a TIF or VRT image using this tool or tilelive copy?

**Comment by gmaclennan** [comment]
Ok, so I dug a little deeper into this. `webp` is hardcoded into both [tilelive-omnivore](https://github.com/mapbox/tilelive-omnivore/) and [tilelive-bridge](https://github.com/mapbox/tilelive-bridge).

I have forked these 3 repos to add support for specifying a format (jpg, png or webp) either by the file extension on the s3url, or with a `--format=jpg` argument. I also added a `--retina=false` argument (defaults to true) for creating non-retina 256x256 tiles (currently `tilelive-bridge` creates retina tiles by default).

This doesn't create any breaking changes, but `mapbox-tile-copy` will break if not using the patched `tilelive-omnivore` since it now passes the uri as an object, which `tilelive-omnivore` does not parse.

https://github.com/mapbox/mapbox-tile-copy/compare/master...digidem:raster-formats?expand=1
https://github.com/mapbox/tilelive-omnivore/compare/master...digidem:raster-formats?expand=1
https://github.com/mapbox/tilelive-bridge/compare/master...digidem:raster-formats?expand=1

**Comment by springmeyer** [comment]
@gmaclennan - just seeing this. If you find this is an important usecase please provide PRs to review. However my strong preference would be to keep the mapbox-tile-copy scope tight and to not add more functionality here unless absolutely necessary.
