### ISSUE TITLE
Can't npm install this (node-pre-gyp errors)

### ISSUE THREAD

**Issue by liebrand** [mapbox/mapbox-tile-copy#47]
I've tried installing this via npm install with various different versions of node (0.10.9, 0.11.0, 0.12.4, 4.2.1, and 5.1.0). All fail, albeit in slightly different ways, but i think all related to node-pre-gyp....

5.1.0 seems to get the furthest, but then ultimately fails with:

> node-pre-gyp install --fallback-to-build
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config libpng --cflags' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/liebrand/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/liebrand/.nvm/versions/node/v5.1.0/bin/node" "/Users/liebrand/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/liebrand/.nvm/versions/node/v5.1.0/lib/node_modules/mapbox-tile-copy/node_modules/tilelive-s3/lib/binding/tilelive_s3.node" "--module_name=tilelive_s3" "--module_path=/Users/liebrand/.nvm/versions/node/v5.1.0/lib/node_modules/mapbox-tile-copy/node_modules/tilelive-s3/lib/binding"
gyp ERR! cwd /Users/liebrand/.nvm/versions/node/v5.1.0/lib/node_modules/mapbox-tile-copy/node_modules/tilelive-s3
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error

**Comment by liebrand** [comment]
In the end I finally got this working by:
1- downgrading my node to 0.12.4
2- brew install zeromq
3- brew install pkgconfig
4- brew install libpng
5- npm install -g mapbox-tile-copy
6- upgrading my node back to v5.1.0

**Comment by martgnz** [comment]
I am getting similar errors as well on OS X. Are there any plans to solve this?

**Comment by rclark** [comment]
These failures likely stem from dependency on https://github.com/mapnik/node-mapnik. Certain versions of node-mapnik are only prebuilt for certain versions of node.js. When node-pre-gyp can't find an acceptable combination of the node-mapnik version you requested and the version of node.js you're running, it falls back to trying to build the c++ addons "from scratch". In these cases, you'll need several other tools installed.

[Looking over the .travis.yml](https://github.com/mapnik/node-mapnik/blob/v3.5.13/.travis.yml#L51-L71) in node-mapnik, I see that there should be builds on v0.10 v4 and v5. Further investigation of the travis logs, looks like pre-built bundles were built on 
- 5.10.1
- 4.4.3
- 0.10.44

**Comment by martgnz** [comment]
Thanks @rclark, I understand now.

I'll switch my node version to `5.10.1` with nvm and try the installation again.

I'll keep you updated.

**Comment by paddoum** [comment]
Switch to 5.10.1 solved it for us.
