### ISSUE TITLE
Clarify valid values for --part parameter

### ISSUE THREAD

**Issue by erikandre** [mapbox/mapbox-tile-copy#56]
I've been using mapbox-tile-copy to process some very large .shp files, using the option to process them in parts.

However, after looking at the documentation I'm still not quite sure about if the --part parameter is zero indexed (e.g. if --parts=10 then valid values for part is 0..9) or if it instead should start at 1 (e.g. if --parts==10 then valid values for part is 1..10).

Trial and error has not really helped me either since I've not reliably been able to process either part 0 or 10 (in case of 10 parts). Sometimes part=0 works (it doesn't contain a lot of tiles though) but most of the time it will just time out (and trying part=10 always seems to time out).

`Error: Copy operation timed out
    at null.<anonymous> (/usr/lib/node_modules/mapbox-tile-copy/node_modules/tilelive/lib/tilelive.js:390:22)
    at wrapper (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)`

It would be great if the documentation could make this a bit more clear :). Thanks and a huge thank you for open sourcing this awesome project!

**Comment by GretaCB** [comment]
👋  @erikandre, thanks so much for your ticket. I ran into a similar copy problem this week, and updated the docs a bit. PR is currently [pending here](https://github.com/mapbox/mapbox-tile-copy/pull/86/files). Parts are definitely zero-indexed.

**Comment by erikandre** [comment]
Thank you @GretaCB  for clearing that up! :)
