### ISSUE TITLE
Allow upgrading crufty v1 tiles in migration stream

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-tile-copy#71]
We gained the ability to migrate vector tiles adhering to the v1 spec version to v2 in #62.

But a problem exists:

  - The v1 spec was not strict (or at least its implementations) about layers with no features.
  - Validation is done [currently in migration-stream.js **before** upgrading](https://github.com/mapbox/mapbox-tile-copy/blob/cca8e80fc57811e7b53e199c8a03a6f7625d2379/lib/migration-stream.js#L37-L65)
  - The validation code currently throws on layers with no features (which are harmless and common). 
  - This means that v1 tiles with empty layers cannot be upgraded and the whole process bails.

Instead, for usecases of `mapbox-tile-copy` like batch migrating large tilesets to v2, we want:

  - Any v1 tile that can be upgraded, is upgraded
  - The resulting v2 tile should be valid

/cc @mapsam @ajashton @GretaCB

**Comment by jakepruitt** [comment]
V1 Validation on a per-tile basis for serialtiles was already in place before we switched to the migration strategy, (refs https://github.com/mapbox/mapbox-tile-copy/blob/4.2.0/lib/serialtilescopy.js#L63-L67). The V1 validation that took place before was with `.setData`, and I *think* (I'm willing to be wrong on this) the validation that is done now should check the same things on V1 tiles as before. Could there be a regression in the V1 validation code?

On the other hand, we used to not do per-tile validation on mbtiles files, so introducing the validation on V1 tiles is definitely a new codepath for V1 tiles that's a consequence of refactoring the tile-copy transform stream to work for both serialtiles and mbtiles. I agree that we should be liberal in what we accept on the mbtiles side, so moving validation to only V2 tiles seems appropriate. I just wonder how we want to maintain the per-tile validation behavior on V1 tiles that we had in place before for serialtiles.
